### ISSUE TITLE
No kbfiltr.inf file

### ISSUE THREAD

**Issue by JPG-Consulting** [Microsoft/Windows-driver-samples#109]
When I compile the kbdfilter project I get no .inf file and therefore installation steps fail. How do you create the .inf file?

During compilation I get:

`Inf2Cat task was skipped as there were no inf files to process`

**Comment by fischmax** [comment]
I have the exact same issue when trying to build with msbuild. Renaming the kbfiltr.inx to kbfiltr.inf makes stampinf run but I am not too sure what is going on there (and I can't run the resulting driver either). I haven't tried building with Visual Studio yet, since I kinda don't want to install it ;)

Also, readme.md speaks of a `[DDK_Ex.Mfg.NT$ARCH$]` section in the inx file which appears to be missing …

**Comment by jcclark53** [comment]
Same issue here, only sys file produced, missing files as in readme:
Kmdfsamples.cat
kbfiltr.inf
WdfCoinstaller010xx.dll

**Comment by ZloiBubr** [comment]
Same issue here, only sys file produced, missing files as in readme:
Kmdfsamples.cat
kbfiltr.inf
WdfCoinstaller010xx.dll

**Comment by fischmax** [comment]
Only slightly related but I need to vent: following these [instructions](https://msdn.microsoft.com/en-us/windows/hardware/drivers/gettingstarted/provision-a-target-computer-wdk-8-1) bricked my target computer. It now just BSODs when booting. This is bad because I kinda need that machine :-(

**Comment by ZloiBubr** [comment]
@fischmax try F8 key and "Last known good configuration"

**Comment by jcclark53** [comment]
😞

Sent from my Windows Phone
________________________________

**Comment by rsachira** [comment]
Add the kbfiltr.inx to the project (Add->Add Existing) then the inf gets generated
