### ISSUE TITLE
Enable WPP Recorder does not work

### ISSUE THREAD

**Issue by akd-jls** [Microsoft/Windows-driver-samples#2]
I tried to enable "Enable WPP Recorder" in Sensors Code. The code throws errors. 

Navigate to Properties->Wpp Tracing->Function and Macro Options and choose Enable WPP Recorder.

**Comment by david1234321** [comment]
What sample were you hitting this on?

**Comment by akd-jls** [comment]
I tried Pedometer driver with VS2013, SDK & WDK File Version 10.0.9926.

https://github.com/Microsoft/Windows-driver-samples/tree/master/sensors/Pedometer

**Comment by jmrossy** [comment]
We've reproed this issue and will address it a future kits release. Thanks for your patience.

**Comment by jmrossy** [comment]
If this issue is blocking you, there's a workaround you can use. Add the following two lines near the bottom of the SensorsTrace.h header.

    #define WPP_RECORDER_LEVEL_FLAGS_SENSOREXIT_FILTER(LEVEL, FLAGS, status)   WPP_RECORDER_LEVEL_FLAGS_FILTER(LEVEL, FLAGS)
    #define WPP_RECORDER_LEVEL_FLAGS_SENSOREXIT_ARGS(LEVEL, FLAGS, status)     WPP_RECORDER_LEVEL_FLAGS_ARGS(LEVEL, FLAGS)

You mentioned above you're using VS2013. For Windows 10 driver development we strongly recommend using the VS2015 preview with the [latest SDK & WDK releases](https://msdn.microsoft.com/en-US/windows/hardware/dn913721(v=vs8.5).aspx "Windows Insiders").
