### ISSUE TITLE
INF issues raised by WHQL signing

### ISSUE THREAD

**Issue by TeraDonawa** [microsoft/Windows-driver-samples#58]
Hi,
   we have built a WDDM display driver based off the sample code, and are running it through WHQL signing.  One of the errors raised has to do with the model section in the INF file.
[Summary of ChkInf results for ._sampledisplay.pdf](https://github.com/Microsoft/Windows-driver-samples/files/205627/Summary.of.ChkInf.results.for._sampledisplay.pdf)

The WHQL test is running the CHKINF utility that's packaged with the Windows Driver Kit 8.1.  the chkinf.bat is a wrapper around the perl script.  The code that reports the problem looks something like this:

```
     `if ( $hwid =~ /.*CC_03.*/i
       or $hwid =~ /.*CLS_0003.*/i)
     {
        AddDisplayError(6036,$Current_INF_File->getIndex($Section,$count));
        next;
     }

     $Devices->{$hwid} = {'DDINSTALL' => $installSectionName, 
                          'DESCRIPTION' => $DevDesc };            
  }`
```

That is, the mere existence of CC_03\* in the model line will cause the chkinf test to fail.  Basically, there is a rule somewhere that the device driver should never claim support for the base VGA or XGA device.

The check obviously wouldn't allow the VGA/XGA devices to even be[ listed as compatible](https://msdn.microsoft.com/en-us/library/windows/hardware/ff547456%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396).

Does anyone know if this chkinf check reasonable, or should it allow for PCI/CC_0300 etc to at least be in the compatible id list?  And if the check is reasonable, how would one get a working INF file without having a physical device (assuming a physical device would provide us with a unique hardware id and satisfy the chkinf check).

**Comment by Tawnos** [comment]
It's years later, but since I wrote the iteration of Display.pm used in Win7/8/8.1 and just came across this thread/recognize this code, I figured I'd answer (after reviewing some specs I haven't looked at in years :)). 

It's doing the right thing. Remember that chkinf was meant for WHQL submission to get approval for drivers to ship on Windows Update. The code prevents a vendor accidentally claiming compatibility with the default display driver and causing their display driver to replace the base OS driver (formerly the XDDM-based VGA driver, now the Basic Display Driver (MSBDD) that is far more capable). As the error text says, a driver may not claim to provide support for these default device identifiers, as that is part of the inf you are meant to update when creating your own driver.
