### ISSUE TITLE
UMDF_FX2 driver mishandles endpoints

### ISSUE THREAD

**Issue by timrprobocom** [Microsoft/Windows-driver-samples#69]
In Device.cpp at line 715, the code is enumerating through the list of endpoints, planning to grab the bulk in and bulk out endpoints in variables.  If it is an IN bulk endpoint, it saves pIUsbPipe in m_pIUsbInputPipe.  If it is an OUT bulk endpoint, it saves pIUsbPipe in m_pIUsbOutputPipe.  Both of thise are simple interface pointers, IWDFUsbTargetPipe *, which means they do not bump the reference count.

But at line 766, it unconditionally calls SAFE_RELEASE(pIUsbPipe), which reduces the reference count to 0, and the object itself is freed.  That means the pointers in m_pIUsbInputPipe and m_pIUsbOutputPipe now point into empty space.  And, indeed, code that uses this model crashes with a null pointer dereference.

Now, if m_pIUsbInputPipe and m_pIUsbOutputPipe were smart pointers like CComPtr or _com_ptr_t (as they should be), this would not be a problem, because the assignment would bump the reference count.  As it is, the code is simply wrong.  You can't release an interface while you still hold uncounted copies of the pointer.

In the original UMDF release in the 6000 Vista WDK, the SAFE_RELEASE was only in the paths that now call DeleteWdfObject.  That is the correct behavior.  The SAFE_RELEASE should be cut from line 766 and pasted twice above, just after the calls to DeleteWdfObject.  By the 7600 WDK, it was broken.

**Comment by Shyamal-V** [comment]
You're right that this is typically not the pattern followed in COM, but UMDF drivers do not need to keep a reference to a framework object after creation of the object. The driver can release the object creation reference immediately because the WDF object tree maintains its reference to it. Although the reference is released early, the device object continues to exist until device is removed because the WDF object tree keeps a reference to it.

Please see the "Managing References to Framework Objects" documentation here - https://msdn.microsoft.com/en-us/windows/hardware/drivers/wdf/managing-the-lifetime-of-objects 

If you're writing a new UMDF driver, you should strongly consider using UMDF V2 instead, which has a KMDF like API surface and the driver does not need to deal with COM interfaces.
